### PR TITLE
add direct paste commands

### PR DESCRIPTION
**Pull request by anselmwang**
This is a PR to solve #11. It adds following commands to the plugin. Do you mind to have a look at it?
image

### CODE REVIEW

**Comment by jglev** [comment]
@anselmwang, thank you for this! And I'm sorry to take this long to respond to your feature requests. I'll take a look this weekend!

**Comment by anselmwang** [comment]
No worry. I enjoy some sunshine this weekend after working for a whole week.

**Comment by jglev** [comment]
@anselmwang, just a quick note to say that I'm still planning to review this soon! I'm planning on implementing some automated tests ASAP, and then use this PR as a chance to try them for the first time in practice.

**Comment by jglev** [comment]
Thank you for this draft, @anselmwang! I've merged the main `2.2.0` branch just now, and so am closing this PR.

**Pull request closed without merging**
